language: node_js
node_js:
- '6'
- '6.1'
- node
cache:
  directories:
  - node_modules
before_deploy: npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: mr.tu@michaelqq.com
  api_key:
    secure: cM6vKVAappEy/RuqXB6qe0IZxdVw4/mH1wNzGcuTV3yRlJa9EFg7iNJpiWRcIJmR+iMESsdqiEiLrGr3YqPY5Cnp/v0JqCWvmqdp6O+NCvvpgaVjQqggjf21lNFpgsjlEjQN7yP/D6Lnv7vV3kg1+KdEiALdnEwcy/rNk4CKbz12tYEfsc7E87jWHWggb5l9D4vAe3Voppyj7ko85LLi0Ddr+egrGj5Srex7m7HmdvuyDhXcyZBr57WPQJSxzC2PeecC35P13I2O3MuKeHhbtmxPG+lnLDV8bFNJL9Mss75TBGAHXm+1gIyKJUuH/rxerHOqDhjImCf7OLNitbZDn3/eHOV08NaMvZViSJ7bi0fSPtoA96LK6jo+0u30NutTjBynN0BbMIwY8QGStkmQyMKS+U0xAy4XFYoupS0/v1fOOVH2EhDn8Uy18GNCinb4C9PXzvIEy2FubkMGDxUQMWC0YSVEJ/3dE2RBllajUo3vDSBJQqYDVq21dhAgHKdVRBSAV/zhVXvyJEGVlriZoltI4iUCfispt2o4RN+1+h+Op+yelMXza8//1+JxvEwqD+YaUfKwcvKyWInZus+dLhHA8ReblE6PxB3T41IOQt5TMngM6JzkbIR8T1GfuDpynyptNzFGi5VsD0uJpFWejoRJYmH0te76BN2ua3md3jk=
  on:
    tags: true
    repo: MichaelQQ/promisecb
