language: node_js
node_js:
- '6'
- '6.1'
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mr.tu@michaelqq.com
  api_key:
    secure: MYHjhGvuN2p1A64QKoccSwME1Jb2CBiuVdy2uMZdALtjUTEAXnGEFPotFJ+yb7EPbHm3jBaj8ylecIklU9XFx+AH6/RBk42Mi2Z1voRAruEzjz5lMLd7Y2g60iKH02OyootIhEWzo7zcTMKv1C2tE8eMcUDkGzK2+igOEU+GfR0ITmGZlH3nBX01akKOsfJJ1PGzdeAG8L0NvuxPdpcBau+O925l69qNmrvcUEe+EdxDfr5f4rM6Y61LYXVFZOnXpYLlsA05VjUD5LAlBQl0DuReUZvS7UWvvNuHLedDtvPP/M+ilxO20Rl5WbMETCwqTy/8TtbhdJYBbwy38x96Luf1WSJifPyrTuEfPIqKJll3xm5xumJbCmjH8F+AtOTihOJKwgC9/Y25Ief+O+7EtEFRQqIJJHtyv4nUd9hiQU7Bq6EEbzLzxcFhiqfeuHkGWU4SODIqGxUaYpvR5sYrpldnMS/ffSq8/APcgbn7R1Y0VoqMuiqexhSFjK7vJZexs32hLIathqAjR05/tqe8VMvbCbOoLv1aDN5YPLLykpS8q9DEdU+h0RCZQE+zpDhhTxoI42tJocSEdLrMyBn8RB2QC9tWn5adjE+5Hdv23am51KHEdm4/dlI0Urh7F0WPyOM4BiBDUM+nSNJW3ItSeXodJnECM5AXqYd+4moRQgE=
  on:
    tags: true
    repo: MichaelQQ/cbPromisify
